name = "dcc-data-source"
main = "src/worker.js"
compatibility_date = "2024-09-01"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "dcc-data-source-db"
database_id = "96d48c57-ab30-4bc4-b6ea-d98c0b02dc1f"
